pythonDj/myFirst/myFirst/apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

pythonDj/myFirst/myFirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls)
]

pythonDj/myFirst/myFirst/apps/articles/models.py
import datetime
from django.utils import timezone
from django.db import models


class Arcticle(models.Model):
    bbb_title = models.CharField('Название статьи', max_length=200)
    bbb_text = models.TextField('Текст статьи')
    bbb_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.bbb_title

    def was_publish_recently(self):
        return self.bbb_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Arcticle, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=55)
    comment_text = models.CharField('Текст комментария', max_length=150)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

pythonDj/myFirst/myFirst/apps/articles/views.py
from django.shortcuts import render
from .models import Arcticle
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    latest_articles_list = Arcticle.objects.order_by('-bbb_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Arcticle.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена!')

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Arcticle.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена!')
    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

pythonDj/myFirst/myFirst/templates/articles/detail.html
{% extends 'base.html'%}

{% block title %}{{article.bbb_title}}}{% endblock %}

{% block content %}

<h2>{{article.bbb_title}}</h2>

<p>{{article.bbb_text}}</p>

<em>{{article.bbb_date}}</em>

<hr>

{% if latest_comments_list %}

    {% for c in latest_comments_list%}
        <p>
            <strong>{{c.author_name}}</strong>
            <p>{{c.comment_text}}</p>
        </p>
    {%endfor%}

{%else%}
Сорри броу комментов пока не наблюдается
{%endif%}

</hr>

<form action="{% url 'articles:leave_comment' article.id %}"method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea>
    <button type="submit">Оставить комментарий</button>


</form>

{% endblock %}

pythonDj/myFirst/myFirst/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.bbb_title}}</a>
        {% endfor %}
    {% else %}
        Сорри бро пока статей нет /(0_0)\
    {% endif %}
{% endblock %}

pythonDj/myFirst/myFirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Топовый сайт{% endblock %}</title>
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>